name: prettier formatting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: format code
        run: format